### ISSUE TITLE
Generates "and" at the end of round hundreds, e.g. "1900 -> One thousand nine hundred and" 

### ISSUE THREAD

**Issue by alisatl** [Suchith-kumar/Digits_To_Words#1]
Hey Suchith, 
Great job on this script, it's actually very useful. 

However, currently it generates and extra "and" at the end of the spelled number if it ends on round hundreds like, e.g., 1100. 

According to this Quora article: 
https://www.quora.com/How-do-I-say-a-long-number-in-English-Do-I-need-spell-and-after-hundred
it is not strictly necessary to add "and" after hundreds if they are followed by tens.  So the easiest way to fix it is just erasing "and". 

Good luck!

**Comment by Suchith-kumar** [comment]
Hey Alisa,
Thanks for the review of my code. I would update it sooner.

**Comment by Suchith-kumar** [comment]
I have updated the code.
